# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: im_depend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'im_depend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import im_pb2 as im__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fim_depend.proto\x12\tim_depend\x1a\x08im.proto\"D\n\nDepMessage\x12\x1e\n\x02\x65n\x18\x01 \x01(\x0e\x32\x12.im_depend.DepEnum\x12\x16\n\x04user\x18\x02 \x01(\x0b\x32\x08.im.User*%\n\x07\x44\x65pEnum\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'im_depend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPENUM']._serialized_start=110
  _globals['_DEPENUM']._serialized_end=147
  _globals['_DEPMESSAGE']._serialized_start=40
  _globals['_DEPMESSAGE']._serialized_end=108
# @@protoc_insertion_point(module_scope)
