# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: im_nested.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'im_nested.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fim_nested.proto\x12\tim_nested\"\xc8\x02\n\x0eInstantMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x36\n\x07nested1\x18\x02 \x01(\x0e\x32%.im_nested.InstantMessage.NestedEnum1\x12\x11\n\tsender_ip\x18\x03 \x01(\x07\x12\x1f\n\x06sender\x18\x04 \x01(\x0b\x32\x0f.im_nested.User\x12\"\n\trecipient\x18\x05 \x01(\x0b\x32\x0f.im_nested.User\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x19\n\x11image_attachments\x18\x07 \x03(\x0c\x12%\n\x08metadata\x18\x08 \x01(\x0b\x32\x13.im_nested.MetaData\"@\n\x0bNestedEnum1\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03\"\'\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0bscreen_name\x18\x02 \x01(\t\"\x91\x03\n\x08MetaData\x12\x30\n\x07nested1\x18\x01 \x01(\x0e\x32\x1f.im_nested.MetaData.NestedEnum1\x12\x0f\n\x07latency\x18\x02 \x01(\x02\x12\x31\n\ninner_data\x18\x03 \x01(\x0b\x32\x1d.im_nested.MetaData.InnerData\x1a\xcc\x01\n\tInnerData\x12:\n\x07nested2\x18\x01 \x01(\x0e\x32).im_nested.MetaData.InnerData.NestedEnum2\x12\x0f\n\x07latency\x18\x02 \x01(\x02\x12\x30\n\x07nested1\x18\x03 \x01(\x0e\x32\x1f.im_nested.MetaData.NestedEnum1\"@\n\x0bNestedEnum2\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03\"@\n\x0bNestedEnum1\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03*W\n\x06\x43lient\x12\x12\n\x0e\x43LIENT_UNKNOWN\x10\x00\x12\x15\n\x11\x43LIENT_NATIVE_APP\x10\x01\x12\x12\n\x0e\x43LIENT_WEB_APP\x10\x02\x12\x0e\n\nCLIENT_API\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'im_nested_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT']._serialized_start=806
  _globals['_CLIENT']._serialized_end=893
  _globals['_INSTANTMESSAGE']._serialized_start=31
  _globals['_INSTANTMESSAGE']._serialized_end=359
  _globals['_INSTANTMESSAGE_NESTEDENUM1']._serialized_start=295
  _globals['_INSTANTMESSAGE_NESTEDENUM1']._serialized_end=359
  _globals['_USER']._serialized_start=361
  _globals['_USER']._serialized_end=400
  _globals['_METADATA']._serialized_start=403
  _globals['_METADATA']._serialized_end=804
  _globals['_METADATA_INNERDATA']._serialized_start=534
  _globals['_METADATA_INNERDATA']._serialized_end=738
  _globals['_METADATA_INNERDATA_NESTEDENUM2']._serialized_start=674
  _globals['_METADATA_INNERDATA_NESTEDENUM2']._serialized_end=738
  _globals['_METADATA_NESTEDENUM1']._serialized_start=295
  _globals['_METADATA_NESTEDENUM1']._serialized_end=359
# @@protoc_insertion_point(module_scope)
