# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: im_package_depend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'im_package_depend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import im_package_depend_dependency_pb2 as im__package__depend__dependency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17im_package_depend.proto\x12\x11im_package_depend\x1a\"im_package_depend_dependency.proto\"[\n\nDepMessage\x12&\n\x02\x65n\x18\x01 \x01(\x0e\x32\x1a.im_package_depend.DepEnum\x12%\n\x04user\x18\x02 \x01(\x0b\x32\x17.im_package_depend.User*%\n\x07\x44\x65pEnum\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'im_package_depend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPENUM']._serialized_start=175
  _globals['_DEPENUM']._serialized_end=212
  _globals['_DEPMESSAGE']._serialized_start=82
  _globals['_DEPMESSAGE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
