# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: im.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'im.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08im.proto\x12\x02im\"\'\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0bscreen_name\x18\x02 \x01(\t\"\xca\x02\n\x08MetaData\x12\x0f\n\x07latency\x18\x01 \x01(\x02\x12!\n\x05inner\x18\x02 \x01(\x0b\x32\x12.im.MetaData.Inner\x1a\x89\x02\n\x05Inner\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\x31\n\x05layer\x18\x03 \x01(\x0b\x32\".im.MetaData.Inner.LimboDreamLayer\x1a\"\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\x1ag\n\x0fLimboDreamLayer\x12)\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x19.im.MetaData.Inner.Client\x12)\n\x06status\x18\x02 \x01(\x0e\x32\x19.im.MetaData.Inner.Status\"*\n\x06Status\x12\x08\n\x04\x44\x45\x41\x44\x10\x00\x12\t\n\x05\x41LIVE\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\"\xd5\x01\n\x0eInstantMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1a\n\x06\x63lient\x18\x02 \x01(\x0e\x32\n.im.Client\x12\x11\n\tsender_ip\x18\x03 \x01(\x07\x12\x18\n\x06sender\x18\x04 \x01(\x0b\x32\x08.im.User\x12\x1b\n\trecipient\x18\x05 \x01(\x0b\x32\x08.im.User\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x19\n\x11image_attachments\x18\x07 \x03(\x0c\x12\x1e\n\x08metadata\x18\x08 \x01(\x0b\x32\x0c.im.MetaData*W\n\x06\x43lient\x12\x12\n\x0e\x43LIENT_UNKNOWN\x10\x00\x12\x15\n\x11\x43LIENT_NATIVE_APP\x10\x01\x12\x12\n\x0e\x43LIENT_WEB_APP\x10\x02\x12\x0e\n\nCLIENT_API\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'im_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT']._serialized_start=606
  _globals['_CLIENT']._serialized_end=693
  _globals['_USER']._serialized_start=16
  _globals['_USER']._serialized_end=55
  _globals['_METADATA']._serialized_start=58
  _globals['_METADATA']._serialized_end=388
  _globals['_METADATA_INNER']._serialized_start=123
  _globals['_METADATA_INNER']._serialized_end=388
  _globals['_METADATA_INNER_CLIENT']._serialized_start=205
  _globals['_METADATA_INNER_CLIENT']._serialized_end=239
  _globals['_METADATA_INNER_LIMBODREAMLAYER']._serialized_start=241
  _globals['_METADATA_INNER_LIMBODREAMLAYER']._serialized_end=344
  _globals['_METADATA_INNER_STATUS']._serialized_start=346
  _globals['_METADATA_INNER_STATUS']._serialized_end=388
  _globals['_INSTANTMESSAGE']._serialized_start=391
  _globals['_INSTANTMESSAGE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
